name: Build-n-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
         node-version: "18.13.0"
      - name: Install dependencies
        run: npm install
      - run: npm run build 
      - run: npm run dev:db-and-api
      - run: npm test
