name: Build-n-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.13.0"
      - name: Create env file
        run: echo "${{ secrets.DEV_ENV_FILE }}" > ./dev.env
      - name: Install dependencies
        run: npm install
      - name: Run DB and backend
        run: npm run dev:db-and-api && sleep 2m && npm run init-db
      - name: Init DB
        run: sleep 2m && npm run init-db
